# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a7b9e8c360ef85a0707326978fe308200edd311cddaadafa261183338ec8b82f0f9750c01a685be74d7d14000ac2855082a37bd2da1cc30c85f5aa05da6010e

test:
  secret_key_base: 3253ae2dd758f1a2afd35b8c75c87a1a47b12f111b778837e57b3af780ad94fb84a5bfe3e90c389d910e51c38dcf23bbbcc71f2598a8310efb27bed97f0b79e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
